name: 'Approval Action'
description: 'This action requests an approval to continue the workflow using issue comments.'

inputs:
  token:
    description: 'The GitHub token used to create the issue.'
    required: true

  approvers:
    description: 'A list of GitHub users that are allowed to approve the workflow.'
    required: true

  issueTitle:
    description: 'The title of the issue that will be created.'
    required: false

  issueBody:
    description: 'The body of the issue that will be created.'
    required: true

  issueLabels:
    description: 'A list of labels that will be added to the issue.'
    required: false

  excludeInitiator:
    description: 'If true, the user that triggered the workflow will not be able to approve the workflow.'
    required: false

  approveWords:
    description: 'A list of words that can be used to approve the workflow.'
    required: false
    default: 'approve, approved'

  rejectWords:
    description: 'A list of words that can be used to disapprove the workflow.'
    required: false
    default: 'deny, denied, reject, rejected'

  waitInterval:
    description: 'The number of minutes to wait before checking for new comments.'
    required: false
    default: 1

  waitTimeout:
    description: 'The number of minutes to wait before timing out.'
    required: false
    default: 360

  minimumApprovals:
    description: 'The minimum number of approvals required to continue the workflow.'
    required: false
    default: 1

outputs:
  approved:
    description: 'A boolean indicating whether the workflow was approved.'
    value: ${{ steps.approval.outputs.approved }}

runs:
  using: 'node20'
  main: 'src/index.js'
