name: Approval - Manual Test

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Approval Action
      id: approval
      uses: ./
      with:
        token: ${{ secrets.GH_PAT }}
        approvers: 'ekeel'
        minimumApprovals: '1'
        issueTitle: 'Manual Test Approval'
        issueBody: |
          This is a manual test approval.
          Please approve or deny this workflow.
        issueLabels: 'ApprovalAction,ManualApproval'
        excludeInitiator: 'false'
        approveWords: 'approve, approved'
        rejectWords: 'deny, denied, reject, rejected'
        waitInterval: '1'
        waitTimeout: '5'

    - name: Get the output
      run: |
        echo "Approved: ${{ steps.approval.outputs.approved }}"